### PR TITLE
#3 waffle.io Badge

### LINKED ISSUE #8: Create Scrum board in Waffle.io

### PR DESCRIPTION
**Pull request by waffle-iron**
This commit closes #8 .
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/Viridovix/show-me-the-code-github

This was requested by a real person (user dawidnejman) on waffle.io, we're not trying to spam you.

### CODE REVIEW

**Comment by mkordas** [comment]
@dawidnejman, I think we should amend Waffle's commit and add `#3` at the beginning of message to keep some convention.

**Comment by nejdaw** [comment]
@mkordas done

**Comment by mkordas** [comment]
I meant that we should change commit message, not only PR description.

**Comment by nejdaw** [comment]
Updated comment. Hope it's fine

**Comment by mkordas** [comment]
@dawidnejman 
Commit still is just `add waffle.io badge`, no issue number there.

**Pull request closed without merging**
