### PR TITLE
#9 Implement plugin skeleton accepted by Chrome

### LINKED ISSUE #9: Implement plugin skeleton accepted by Chrome
We need an application skeleton which can be built and will be recognised by Chrome as a plugin.

### PR DESCRIPTION
**Pull request by balawama**
Closes #9 

Sample:
sample

sample2

### CODE REVIEW

**Comment by balawama** [comment]
@mkordas how is it going with #7 ? Builds for my PR failed :)

**Comment by mkordas** [comment]
@balawama
#20 is ready to review and merge

**Comment by mkordas** [comment]
Build failures should be gone whenever commit hash will change to the new one

**Comment by balawama** [comment]
New commit hash introduced, pls review

**Comment by nejdaw** [comment]
:+1:

**Comment by balawama** [comment]
Wooo hooo :)
24 paź 2015 14:04 "Dawid Nejman" notifications@github.com napisał(a):

**Pull request merged**
